<?php

/**
 * @file
 * Module file for password_encrypt.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */

/**
 * Implements hook_page_attachments_alter().
 */
function clear_password_field_page_attachments_alter(&$page) {
  $clear_password_field = Drupal::state()->get('clear_password_field.passkey');
  $page['#attached']['library'][] = 'clear_password_field/clear_password_fieldlib';
}

